#:schema node_modules/wrangler/config-schema.json
name = "1"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "707632cc18ae4c43886be9bebe55a265" }
]

[assets]
directory = "./public"
